Pages/AddPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using KatalogSamochodowy.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using System.IO;
using Microsoft.AspNetCore.Hosting;


namespace KatalogSamochodowy.Pages
{
    public class AddPageModel : PageModel
    {
        private readonly ApplicationDbContext _db;
     
        public AddPageModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public Samochod Samochod { get; set; }


        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(IFormFile[] photos)
        {
            if (photos != null && photos.Length > 0)
            {
                foreach (var photo in photos)
                {
                    string saveplace = Path.Combine(Environment.CurrentDirectory, "wwwroot", "lib");
                    string filePath = Path.Combine(saveplace, photo.FileName);

                    using (var file = System.IO.File.Create(filePath))
                    {
                        await photo.CopyToAsync(file);
                    }

                    Samochod.CarPhoto = photo.FileName;
                }
            }
            else
                Samochod.CarPhoto = "brakzdjecia.png";
           

            _db.Add(Samochod);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");

            
        }

            
    }
}

Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KatalogSamochodowy.Pages
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using KatalogSamochodowy.Model;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace KatalogSamochodowy.Pages
{
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }
        

        [BindProperty]
        public Samochod Samochod { get; set; }

        public void OnGet(int Id)
        {
            Samochod = _db.Samochod.Find(Id);
        }

        public async Task<IActionResult> OnPostAsync(IFormFile[] photos, int Id)
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }
            var SamochodFromDb = await _db.Samochod.FindAsync(Samochod.Id);

            if (SamochodFromDb.CarPhoto != null)
            {
                string saveplace = Path.Combine(Environment.CurrentDirectory, "wwwroot", "lib");
                string filePath = Path.Combine(saveplace, SamochodFromDb.CarPhoto);
                System.IO.File.Delete(filePath);
            }

            SamochodFromDb.BrandName = Samochod.BrandName;
            SamochodFromDb.ModelName = Samochod.ModelName;
            SamochodFromDb.Segment = Samochod.Segment;
            SamochodFromDb.BodyType = Samochod.BodyType;
            SamochodFromDb.Description = Samochod.Description;
            SamochodFromDb.Horsepower = Samochod.Horsepower;
            SamochodFromDb.Price = Samochod.Price;
            SamochodFromDb.YearOfProduction = Samochod.YearOfProduction;

            if (photos != null && photos.Length > 0)
            {
                foreach (var photo in photos)
                {
                    string saveplace = Path.Combine(Environment.CurrentDirectory, "wwwroot", "lib");
                    string filePath = Path.Combine(saveplace, photo.FileName);

                    using (var file = System.IO.File.Create(filePath))
                    {
                        await photo.CopyToAsync(file);
                    }

                    SamochodFromDb.CarPhoto = photo.FileName;
                }
            }
            else
            {
                Samochod.CarPhoto = "brakzdjecia.png";
            }

            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace KatalogSamochodowy.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace KatalogSamochodowy.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatalogSamochodowy.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/ShowMore.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KatalogSamochodowy.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KatalogSamochodowy.Pages
{
    public class ShowMoreModel : PageModel
    {
        private ApplicationDbContext _db;
        [BindProperty]
        public Samochod Samochod { get; set; }
        public ShowMoreModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet(int Id)
        {
            Samochod = _db.Samochod.Find(Id);
        }
    }
}

Pages/przeglad.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using KatalogSamochodowy.Model;
using System.IO;



namespace KatalogSamochodowy.Pages
{
    public class przegladModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        //[BindProperty]
        //public  Samochod Samochod { get; set; }

        public IEnumerable<Samochod> Samochod { get; set; }
        public przegladModel (ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task OnGet ()
        {
            Samochod = await _db.Samochod.ToListAsync();
        }


        public async Task<IActionResult> OnPostDelete(int Id)
        {
            var samochod = await _db.Samochod.FindAsync(Id);
            if (samochod == null)
            {
                return NotFound();
            }

            _db.Samochod.Remove(samochod);

            await _db.SaveChangesAsync();
            if (samochod.CarPhoto != null)
            {
                string saveplace = Path.Combine(Environment.CurrentDirectory, "wwwroot", "lib");
                string filePath = Path.Combine(saveplace, samochod.CarPhoto);
                System.IO.File.Delete(filePath);
            }
            

            return RedirectToPage("/przeglad");
        }

    }
}

Pages/AddPage.cshtml
@page
@model KatalogSamochodowy.Pages.AddPageModel
@{
}

<br />
   <h2 class="text-info">Dodaj samochód do katalogu</h2>
<br />

<div class="border">
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container" style="padding:30px">

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.BrandName"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.BrandName" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.BrandName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.ModelName"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.ModelName" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.ModelName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Segment"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Segment" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Segment" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.BodyType"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.BodyType" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.BodyType" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Description"></label>
                    </div>
                    <div class="col-sm-4 ">
                        <textarea asp-for="Samochod.Description" class="form-control" rows="5"></textarea>
                    </div>
                    <span asp-validation-for="Samochod.Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Horsepower"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Horsepower" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Horsepower" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Price"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Price" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.YearOfProduction"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.YearOfProduction" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.YearOfProduction" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.CarPhoto" for="photoss"></label>
                    </div>
                    <div class="col-sm-4">
                        <input id="photoss" name="photos" multiple="multiple" type="file" asp-for="Samochod.CarPhoto" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.CarPhoto" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <input type="submit" value="Dodaj" class="btn-primary form-control" />
                    </div>
                    <div class="col-sm-2">
                        <a asp-page="Index" class="btn-success form-control">Wróć</a>
                    </div>
                </div>
            </div>



        </div>    
    </form>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
 }

Pages/Details.cshtml
@page
@model KatalogSamochodowy.Pages.DetailsModel
@{
}

Pages/Edit.cshtml
@page
@model KatalogSamochodowy.Pages.EditModel
@{
}

<br />
<h2 class="text-info">Edytuj samochód w katalogu</h2>
<br />

<div class="border">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Samochod.Id"/>
        <div class="container" style="padding:30px">

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.BrandName"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.BrandName" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.BrandName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.ModelName"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.ModelName" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.ModelName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Segment"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Segment" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Segment" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.BodyType"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.BodyType" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.BodyType" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Description"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Description" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Horsepower"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Horsepower" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Horsepower" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.Price"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.Price" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.YearOfProduction"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Samochod.YearOfProduction" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.YearOfProduction" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Samochod.CarPhoto"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="file" asp-for="Samochod.CarPhoto" class="form-control" />
                    </div>
                    <span asp-validation-for="Samochod.CarPhoto" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <input type="submit" value="Edytuj" class="btn-primary form-control" />
                    </div>
                    <div class="col-sm-2">
                        <a asp-page="Index" class="btn-success form-control">Wróć</a>
                    </div>
                </div>
            </div>



        </div>
    </form>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<head>
    <link rel="stylesheet" href="~/css/index.css" />
</head>

<body>
    <div class="center">
        <h1 class="display">Witaj w katalogu samochodowym!</h1>

        <div class="check">

            <div>
                <a class="seemore color1" asp-area="" asp-page="/przeglad"><h2>Przeglądaj katalog</h2></a>
            </div>
            <div>
                <a class="seemore color1" asp-area="" asp-page="/AddPage"><h2>Dodaj samochód do katalogu</h2></a>
            </div>



        </div>
        
        
    </div>
    
        

</body>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KatalogSamochodowy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/index.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar1 font-weight-bold" asp-area="" asp-page="/przeglad">Katalog Samochodowy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link navbar1" asp-area="" asp-page="/Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar1" asp-area="" asp-page="/AddPage">Dodaj</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar1" asp-area="" asp-page="/Privacy">Polityka prywatności</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KatalogSamochodowy - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/ShowMore.cshtml
@page
@model KatalogSamochodowy.Pages.ShowMoreModel
@{
}



<table class= "text-light table table-responsive table-striped border text-center ">
	<tbody>
        <tr>
            <th width="15%">
                <label asp-for="Samochod.BrandName" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.ModelName" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.Segment" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.BodyType" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.Horsepower" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.Price" for="BrandName"></label>
            </th>
            <th width="15%">
                <label asp-for="Samochod.YearOfProduction" for="BrandName"></label>
            </th>


        </tr>
        <tr>
            <td>
                <label asp-for="Samochod.BrandName" id="BrandName" class="form-label">@Model.Samochod.BrandName</label>
            </td>
            <td>
                <label asp-for="Samochod.ModelName" id="BrandName" class="form-label">@Model.Samochod.ModelName</label>
            </td>
            <td>
                <label asp-for="Samochod.Segment" id="BrandName" class="form-label">@Model.Samochod.Segment</label>
            </td>
            <td>
                <label asp-for="Samochod.BodyType" id="BrandName" class="form-label">@Model.Samochod.BodyType</label>
            </td>
            <td>
                <label asp-for="Samochod.Horsepower" id="BrandName" class="form-label">@Model.Samochod.Horsepower</label>
            <td>
                <label asp-for="Samochod.Price" id="BrandName" class="form-label">@Model.Samochod.Price</label>
            </td>
            <td>
                <label asp-for="Samochod.YearOfProduction" id="BrandName" class="form-label">@Model.Samochod.YearOfProduction</label>
            </td>
            
        </tr>
        
		
	</tbody>
</table>
<table class= "text-light table table-responsive table-striped border text-center">
    <tr>

        <td class="col">
            <textarea class="form-control text-white  btn-outline-secondary justify-content-around " disabled="disabled" readonly="readonly" id="Description" rows="15" asp-for="Samochod.Description">@Model.Samochod.Description</textarea>
        </td>
        
        <td class="col">
            @if (Model.Samochod.CarPhoto != null)
            {
                <img src="/lib/@Model.Samochod.CarPhoto" width="750" alt="Brak zdjecia" />
            }
        </td>
    </tr>
</table>
<div class="text-end">
    <a asp-page="/przeglad" class="btn btn-danger">Powrót</a>
</div>

Pages/przeglad.cshtml
@page
@model KatalogSamochodowy.Pages.przegladModel
@{
}



<form method="post">
    @if (Model.Samochod.Count() > 0)
    {
        <br /><br />
        
            <table class=" text-light table table-responsive table-striped border text-center ">
                <tr>
                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().BrandName)
                    </th>

                    <th width="13%" >
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().ModelName)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().Segment)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().BodyType)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().Description)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().Horsepower)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().Price)
                    </th>

                    <th width="13%">
                        @Html.DisplayNameFor(m => m.Samochod.FirstOrDefault().YearOfProduction)
                    </th>

                   
                </tr>
                    
                @foreach (var item in Model.Samochod)
                {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.BrandName)
                </td>
                <td>
                    @Html.DisplayFor(m => item.ModelName)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Segment)
                </td>
                <td>
                    @Html.DisplayFor(m => item.BodyType)
                </td>
                <td>
                    <a asp-page="/ShowMore" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Otwórz</a>
                </td>
                <td>
                    @Html.DisplayFor(m => item.Horsepower) HP
                </td>
                <td>
                    @Html.DisplayFor(m => item.Price) ZŁ
                </td>
                <td>
                    @Html.DisplayFor(m => item.YearOfProduction)
                </td>
                

                <td>
                    <button asp-page-handler="Delete" asp-route-id="@item.Id"
                            onclick="return confirm('Jesteś pewien, że chcesz usunąć samochód z katalogu?')"
                            class="btn btn-danger btn-sm">
                        Usuń
                    </button>
                </td>
                <td>
                    <a asp-route-id="@item.Id" asp-page="Edit" class="btn btn-success btn-sm">Edytuj</a>
                </td>
            </tr>

                }
            </table>
        
    }
    else

    {
        <p>
            Brak samochodów w katalogu.
        </p>
    }

</form>